[2023-05-16T13:27:55.333+0000] {processor.py:156} INFO - Started process (PID=4728) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T13:27:55.334+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T13:27:55.335+0000] {logging_mixin.py:149} INFO - [2023-05-16T13:27:55.335+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T13:27:55.339+0000] {logging_mixin.py:149} INFO - [2023-05-16T13:27:55.338+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T13:27:55.340+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T13:27:55.391+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2023-05-16T13:28:35.065+0000] {processor.py:156} INFO - Started process (PID=30) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T13:28:35.066+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T13:28:35.066+0000] {logging_mixin.py:149} INFO - [2023-05-16T13:28:35.066+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T13:28:35.068+0000] {logging_mixin.py:149} INFO - [2023-05-16T13:28:35.067+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T13:28:35.069+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T13:28:35.086+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.023 seconds
[2023-05-16T13:32:57.602+0000] {processor.py:156} INFO - Started process (PID=82) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T13:32:57.603+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T13:32:57.604+0000] {logging_mixin.py:149} INFO - [2023-05-16T13:32:57.603+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T13:32:57.611+0000] {logging_mixin.py:149} INFO - [2023-05-16T13:32:57.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T13:32:57.612+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T13:32:57.645+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2023-05-16T13:46:20.283+0000] {processor.py:156} INFO - Started process (PID=141) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T13:46:20.285+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T13:46:20.286+0000] {logging_mixin.py:149} INFO - [2023-05-16T13:46:20.286+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T13:46:20.290+0000] {logging_mixin.py:149} INFO - [2023-05-16T13:46:20.288+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T13:46:20.290+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T13:46:20.392+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.114 seconds
[2023-05-16T21:07:55.990+0000] {processor.py:156} INFO - Started process (PID=31) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:07:55.991+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:07:55.992+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:07:55.992+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:07:55.994+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:07:55.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:07:55.994+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:07:56.015+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.027 seconds
[2023-05-16T21:08:26.416+0000] {processor.py:156} INFO - Started process (PID=90) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:08:26.417+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:08:26.417+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:08:26.417+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:08:26.419+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:08:26.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:08:26.419+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:08:26.437+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.023 seconds
[2023-05-16T21:08:56.529+0000] {processor.py:156} INFO - Started process (PID=149) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:08:56.530+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:08:56.533+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:08:56.533+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:08:56.542+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:08:56.540+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:08:56.543+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:08:56.572+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2023-05-16T21:09:26.623+0000] {processor.py:156} INFO - Started process (PID=208) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:09:26.624+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:09:26.625+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:09:26.625+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:09:26.627+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:09:26.626+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:09:26.628+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:09:26.762+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.143 seconds
[2023-05-16T21:09:57.360+0000] {processor.py:156} INFO - Started process (PID=266) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:09:57.361+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:09:57.361+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:09:57.361+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:09:57.365+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:09:57.364+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:09:57.365+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:09:57.390+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:10:27.919+0000] {processor.py:156} INFO - Started process (PID=325) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:10:27.920+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:10:27.921+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:10:27.921+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:10:27.924+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:10:27.923+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:10:27.925+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:10:27.945+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2023-05-16T21:10:58.388+0000] {processor.py:156} INFO - Started process (PID=384) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:10:58.396+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:10:58.397+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:10:58.396+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:10:58.400+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:10:58.399+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:10:58.401+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:10:58.428+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.045 seconds
[2023-05-16T21:11:28.999+0000] {processor.py:156} INFO - Started process (PID=443) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:11:29.006+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:11:29.007+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:11:29.007+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:11:29.011+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:11:29.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:11:29.011+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:11:29.044+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2023-05-16T21:11:59.370+0000] {processor.py:156} INFO - Started process (PID=502) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:11:59.377+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:11:59.378+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:11:59.378+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:11:59.381+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:11:59.380+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:11:59.382+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:11:59.402+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2023-05-16T21:12:29.692+0000] {processor.py:156} INFO - Started process (PID=561) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:12:29.699+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:12:29.700+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:12:29.700+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:12:29.703+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:12:29.702+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:12:29.704+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:12:29.725+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2023-05-16T21:13:00.243+0000] {processor.py:156} INFO - Started process (PID=619) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:13:00.250+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:13:00.251+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:13:00.250+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:13:00.254+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:13:00.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:13:00.255+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:13:00.282+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2023-05-16T21:13:30.722+0000] {processor.py:156} INFO - Started process (PID=678) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:13:30.730+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:13:30.731+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:13:30.730+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:13:30.734+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:13:30.733+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:13:30.735+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:13:30.754+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:14:01.072+0000] {processor.py:156} INFO - Started process (PID=737) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:14:01.079+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:14:01.080+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:14:01.080+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:14:01.084+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:14:01.083+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:14:01.084+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:14:01.103+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:14:31.535+0000] {processor.py:156} INFO - Started process (PID=796) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:14:31.542+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:14:31.543+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:14:31.543+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:14:31.546+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:14:31.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:14:31.547+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:14:31.567+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:15:01.953+0000] {processor.py:156} INFO - Started process (PID=855) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:15:01.960+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:15:01.961+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:15:01.960+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:15:01.964+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:15:01.963+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:15:01.965+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:15:01.983+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:15:32.546+0000] {processor.py:156} INFO - Started process (PID=914) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:15:32.553+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:15:32.554+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:15:32.554+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:15:32.557+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:15:32.556+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:15:32.558+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:15:32.585+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2023-05-16T21:16:03.074+0000] {processor.py:156} INFO - Started process (PID=973) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:16:03.075+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:16:03.076+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:16:03.076+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:16:03.079+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:16:03.078+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:16:03.080+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:16:03.100+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2023-05-16T21:16:33.715+0000] {processor.py:156} INFO - Started process (PID=1033) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:16:33.722+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:16:33.723+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:16:33.723+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:16:33.726+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:16:33.725+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:16:33.727+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:16:33.747+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2023-05-16T21:17:04.363+0000] {processor.py:156} INFO - Started process (PID=1092) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:17:04.370+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:17:04.370+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:17:04.370+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:17:04.372+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:17:04.371+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:17:04.372+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:17:04.390+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2023-05-16T21:17:34.825+0000] {processor.py:156} INFO - Started process (PID=1151) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:17:34.825+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:17:34.826+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:17:34.826+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:17:34.827+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:17:34.827+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:17:34.828+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:17:34.848+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2023-05-16T21:18:05.034+0000] {processor.py:156} INFO - Started process (PID=1210) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:18:05.041+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:18:05.041+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:18:05.041+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:18:05.044+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:18:05.042+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:18:05.044+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:18:05.060+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.028 seconds
[2023-05-16T21:18:35.362+0000] {processor.py:156} INFO - Started process (PID=1269) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:18:35.363+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:18:35.363+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:18:35.363+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:18:35.365+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:18:35.364+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:18:35.365+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:18:35.383+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.023 seconds
[2023-05-16T21:19:05.923+0000] {processor.py:156} INFO - Started process (PID=1328) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:19:05.930+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:19:05.931+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:19:05.931+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:19:05.934+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:19:05.933+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:19:05.935+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:19:05.955+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:19:36.388+0000] {processor.py:156} INFO - Started process (PID=1386) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:19:36.389+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:19:36.390+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:19:36.390+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:19:36.394+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:19:36.393+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:19:36.395+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:19:36.418+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2023-05-16T21:20:06.763+0000] {processor.py:156} INFO - Started process (PID=1445) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:20:06.771+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:20:06.772+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:20:06.771+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:20:06.775+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:20:06.774+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:20:06.776+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:20:06.794+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:20:37.322+0000] {processor.py:156} INFO - Started process (PID=1505) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:20:37.323+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:20:37.324+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:20:37.324+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:20:37.328+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:20:37.326+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:20:37.328+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:20:37.345+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.028 seconds
[2023-05-16T21:21:07.726+0000] {processor.py:156} INFO - Started process (PID=1564) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:21:07.727+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:21:07.727+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:21:07.727+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:21:07.729+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:21:07.728+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:21:07.729+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:21:07.747+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.026 seconds
[2023-05-16T21:21:38.043+0000] {processor.py:156} INFO - Started process (PID=1623) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:21:38.044+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:21:38.045+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:21:38.045+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:21:38.049+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:21:38.047+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:21:38.049+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:21:38.070+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2023-05-16T21:22:08.429+0000] {processor.py:156} INFO - Started process (PID=1682) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:22:08.436+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:22:08.437+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:22:08.437+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:22:08.441+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:22:08.439+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:22:08.441+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:22:08.458+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2023-05-16T21:22:38.877+0000] {processor.py:156} INFO - Started process (PID=1741) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:22:38.878+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:22:38.878+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:22:38.878+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:22:38.880+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:22:38.879+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:22:38.880+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:22:38.896+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.021 seconds
[2023-05-16T21:23:09.231+0000] {processor.py:156} INFO - Started process (PID=1800) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:23:09.232+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:23:09.232+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:23:09.232+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:23:09.234+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:23:09.233+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:23:09.234+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:23:09.256+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.027 seconds
[2023-05-16T21:23:39.668+0000] {processor.py:156} INFO - Started process (PID=1859) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:23:39.675+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:23:39.676+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:23:39.676+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:23:39.680+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:23:39.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:23:39.680+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:23:39.705+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.042 seconds
[2023-05-16T21:24:10.024+0000] {processor.py:156} INFO - Started process (PID=1917) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:24:10.031+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:24:10.033+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:24:10.032+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:24:10.036+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:24:10.035+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:24:10.036+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:24:10.056+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2023-05-16T21:24:40.294+0000] {processor.py:156} INFO - Started process (PID=1976) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:24:40.301+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:24:40.302+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:24:40.302+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:24:40.304+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:24:40.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:24:40.304+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:24:40.323+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2023-05-16T21:25:10.614+0000] {processor.py:156} INFO - Started process (PID=2035) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:25:10.614+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:25:10.615+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:25:10.615+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:25:10.617+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:25:10.616+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:25:10.617+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:25:10.633+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.021 seconds
[2023-05-16T21:25:41.083+0000] {processor.py:156} INFO - Started process (PID=2093) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:25:41.091+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:25:41.091+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:25:41.091+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:25:41.095+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:25:41.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:25:41.096+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:25:41.115+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:26:11.474+0000] {processor.py:156} INFO - Started process (PID=2153) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:26:11.475+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:26:11.475+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:26:11.475+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:26:11.477+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:26:11.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:26:11.477+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:26:11.494+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.022 seconds
[2023-05-16T21:26:41.844+0000] {processor.py:156} INFO - Started process (PID=2212) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:26:41.845+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:26:41.845+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:26:41.845+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:26:41.847+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:26:41.846+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:26:41.847+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:26:41.864+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.022 seconds
[2023-05-16T21:27:12.362+0000] {processor.py:156} INFO - Started process (PID=2271) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:27:12.369+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:27:12.371+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:27:12.370+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:27:12.374+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:27:12.373+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:27:12.375+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:27:12.396+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
[2023-05-16T21:27:42.805+0000] {processor.py:156} INFO - Started process (PID=2331) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:27:42.807+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:27:42.808+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:27:42.807+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:27:42.811+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:27:42.810+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:27:42.812+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:27:42.830+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2023-05-16T21:28:13.086+0000] {processor.py:156} INFO - Started process (PID=2390) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:28:13.094+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:28:13.095+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:28:13.094+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:28:13.098+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:28:13.097+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:28:13.099+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:28:13.120+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2023-05-16T21:28:43.488+0000] {processor.py:156} INFO - Started process (PID=2449) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:28:43.489+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:28:43.490+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:28:43.489+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:28:43.493+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:28:43.492+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:28:43.494+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:28:43.512+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2023-05-16T21:29:13.776+0000] {processor.py:156} INFO - Started process (PID=2508) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:29:13.783+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:29:13.784+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:29:13.784+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:29:13.787+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:29:13.786+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:29:13.787+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:29:13.812+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2023-05-16T21:29:44.187+0000] {processor.py:156} INFO - Started process (PID=2567) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:29:44.188+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:29:44.189+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:29:44.189+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:29:44.193+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:29:44.191+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:29:44.193+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:29:44.223+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2023-05-16T21:30:14.771+0000] {processor.py:156} INFO - Started process (PID=2625) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:30:14.778+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:30:14.779+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:30:14.779+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:30:14.782+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:30:14.781+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:30:14.783+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:30:14.801+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:30:45.222+0000] {processor.py:156} INFO - Started process (PID=2684) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:30:45.229+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:30:45.230+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:30:45.230+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:30:45.234+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:30:45.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:30:45.234+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:30:45.253+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:31:15.829+0000] {processor.py:156} INFO - Started process (PID=2744) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:31:15.836+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:31:15.837+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:31:15.837+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:31:15.838+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:31:15.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:31:15.839+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:31:15.855+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2023-05-16T21:31:46.222+0000] {processor.py:156} INFO - Started process (PID=2803) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:31:46.229+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:31:46.230+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:31:46.230+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:31:46.233+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:31:46.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:31:46.234+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:31:46.251+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2023-05-16T21:32:16.838+0000] {processor.py:156} INFO - Started process (PID=2862) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:32:16.845+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:32:16.846+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:32:16.846+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:32:16.849+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:32:16.848+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:32:16.850+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:32:16.868+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2023-05-16T21:32:47.400+0000] {processor.py:156} INFO - Started process (PID=2921) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:32:47.407+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:32:47.408+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:32:47.408+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:32:47.412+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:32:47.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:32:47.412+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:32:47.431+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:33:18.000+0000] {processor.py:156} INFO - Started process (PID=2980) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:33:18.007+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:33:18.009+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:33:18.008+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:33:18.012+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:33:18.011+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:33:18.013+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:33:18.031+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:33:48.542+0000] {processor.py:156} INFO - Started process (PID=3039) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:33:48.543+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:33:48.544+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:33:48.544+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:33:48.547+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:33:48.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:33:48.548+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:33:48.574+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2023-05-16T21:34:19.016+0000] {processor.py:156} INFO - Started process (PID=3098) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:34:19.017+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:34:19.017+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:34:19.017+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:34:19.019+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:34:19.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:34:19.019+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:34:19.037+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.023 seconds
[2023-05-16T21:34:49.571+0000] {processor.py:156} INFO - Started process (PID=3157) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:34:49.578+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:34:49.579+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:34:49.579+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:34:49.581+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:34:49.580+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:34:49.581+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:34:49.600+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2023-05-16T21:35:20.008+0000] {processor.py:156} INFO - Started process (PID=3216) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:35:20.015+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:35:20.016+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:35:20.016+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:35:20.019+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:35:20.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:35:20.020+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:35:20.051+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2023-05-16T21:35:50.315+0000] {processor.py:156} INFO - Started process (PID=3275) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:35:50.316+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:35:50.317+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:35:50.317+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:35:50.319+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:35:50.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:35:50.319+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:35:50.335+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.022 seconds
[2023-05-16T21:36:20.704+0000] {processor.py:156} INFO - Started process (PID=3334) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:36:20.712+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:36:20.713+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:36:20.713+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:36:20.716+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:36:20.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:36:20.717+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:36:20.748+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2023-05-16T21:36:51.160+0000] {processor.py:156} INFO - Started process (PID=3393) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:36:51.161+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:36:51.162+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:36:51.162+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:36:51.166+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:36:51.164+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:36:51.166+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:36:51.193+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2023-05-16T21:37:21.698+0000] {processor.py:156} INFO - Started process (PID=3452) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:37:21.699+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:37:21.700+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:37:21.700+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:37:21.704+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:37:21.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:37:21.705+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:37:21.723+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2023-05-16T21:37:51.981+0000] {processor.py:156} INFO - Started process (PID=3511) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:37:51.981+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:37:51.981+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:37:51.981+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:37:51.983+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:37:51.982+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:37:51.983+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:37:52.003+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2023-05-16T21:38:22.446+0000] {processor.py:156} INFO - Started process (PID=3569) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:38:22.453+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:38:22.454+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:38:22.454+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:38:22.458+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:38:22.456+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:38:22.458+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:38:22.479+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
[2023-05-16T21:38:52.950+0000] {processor.py:156} INFO - Started process (PID=3628) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:38:52.957+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:38:52.958+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:38:52.958+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:38:52.962+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:38:52.960+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:38:52.962+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:38:52.981+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2023-05-16T21:39:23.509+0000] {processor.py:156} INFO - Started process (PID=3687) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:39:23.516+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:39:23.517+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:39:23.517+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:39:23.521+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:39:23.519+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:39:23.521+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:39:23.549+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.045 seconds
[2023-05-16T21:39:53.906+0000] {processor.py:156} INFO - Started process (PID=3747) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:39:53.913+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:39:53.914+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:39:53.914+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:39:53.917+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:39:53.916+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:39:53.918+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:39:53.937+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:40:24.388+0000] {processor.py:156} INFO - Started process (PID=3807) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:40:24.396+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:40:24.397+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:40:24.396+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:40:24.400+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:40:24.399+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:40:24.401+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:40:24.421+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2023-05-16T21:40:54.920+0000] {processor.py:156} INFO - Started process (PID=3867) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:40:54.928+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:40:54.929+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:40:54.929+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:40:54.932+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:40:54.931+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:40:54.933+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:40:54.950+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:41:25.288+0000] {processor.py:156} INFO - Started process (PID=3926) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:41:25.296+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:41:25.296+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:41:25.296+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:41:25.298+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:41:25.298+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:41:25.299+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:41:25.316+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2023-05-16T21:41:55.660+0000] {processor.py:156} INFO - Started process (PID=3985) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:41:55.667+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:41:55.668+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:41:55.668+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:41:55.672+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:41:55.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:41:55.672+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:41:55.693+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2023-05-16T21:42:26.276+0000] {processor.py:156} INFO - Started process (PID=4051) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:42:26.284+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:42:26.285+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:42:26.284+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:42:26.288+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:42:26.287+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:42:26.289+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:42:26.307+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:42:56.777+0000] {processor.py:156} INFO - Started process (PID=4110) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:42:56.784+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:42:56.786+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:42:56.785+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:42:56.790+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:42:56.788+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:42:56.790+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:42:56.811+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
[2023-05-16T21:43:27.382+0000] {processor.py:156} INFO - Started process (PID=4169) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:43:27.390+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:43:27.391+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:43:27.390+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:43:27.394+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:43:27.393+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:43:27.395+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:43:27.414+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:43:57.884+0000] {processor.py:156} INFO - Started process (PID=4228) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:43:57.885+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:43:57.886+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:43:57.886+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:43:57.890+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:43:57.888+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:43:57.890+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:43:57.911+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2023-05-16T21:44:28.450+0000] {processor.py:156} INFO - Started process (PID=4287) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:44:28.450+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:44:28.451+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:44:28.451+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:44:28.452+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:44:28.452+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:44:28.452+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:44:28.470+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.022 seconds
[2023-05-16T21:44:59.070+0000] {processor.py:156} INFO - Started process (PID=4345) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:44:59.078+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:44:59.079+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:44:59.078+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:44:59.082+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:44:59.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:44:59.082+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:44:59.108+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2023-05-16T21:45:29.610+0000] {processor.py:156} INFO - Started process (PID=4404) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:45:29.611+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:45:29.612+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:45:29.612+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:45:29.616+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:45:29.614+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:45:29.616+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:45:29.644+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2023-05-16T21:46:00.180+0000] {processor.py:156} INFO - Started process (PID=4463) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:46:00.187+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:46:00.188+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:46:00.188+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:46:00.192+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:46:00.190+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:46:00.192+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:46:00.219+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2023-05-16T21:46:30.666+0000] {processor.py:156} INFO - Started process (PID=4522) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:46:30.673+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:46:30.674+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:46:30.674+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:46:30.678+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:46:30.676+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:46:30.678+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:46:30.706+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2023-05-16T21:47:00.749+0000] {processor.py:156} INFO - Started process (PID=4582) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:47:00.757+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:47:00.758+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:47:00.758+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:47:00.761+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:47:00.760+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:47:00.762+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:47:00.789+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2023-05-16T21:47:31.068+0000] {processor.py:156} INFO - Started process (PID=4641) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:47:31.075+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:47:31.076+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:47:31.076+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:47:31.079+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:47:31.078+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:47:31.080+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:47:31.108+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.045 seconds
[2023-05-16T21:48:01.201+0000] {processor.py:156} INFO - Started process (PID=4700) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:48:01.202+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:48:01.203+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:48:01.202+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:48:01.206+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:48:01.205+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:48:01.207+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:48:01.225+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2023-05-16T21:48:31.484+0000] {processor.py:156} INFO - Started process (PID=4759) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:48:31.491+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:48:31.492+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:48:31.492+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:48:31.496+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:48:31.494+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:48:31.496+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:48:31.520+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2023-05-16T21:49:02.049+0000] {processor.py:156} INFO - Started process (PID=4818) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:49:02.057+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:49:02.058+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:49:02.057+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:49:02.061+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:49:02.060+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:49:02.062+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:49:02.082+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2023-05-16T21:49:32.228+0000] {processor.py:156} INFO - Started process (PID=4877) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:49:32.235+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:49:32.236+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:49:32.236+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:49:32.239+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:49:32.238+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:49:32.240+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:49:32.258+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:50:02.351+0000] {processor.py:156} INFO - Started process (PID=4936) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:50:02.352+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:50:02.353+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:50:02.352+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:50:02.356+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:50:02.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:50:02.357+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:50:02.378+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2023-05-16T21:50:32.748+0000] {processor.py:156} INFO - Started process (PID=4996) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:50:32.754+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:50:32.755+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:50:32.755+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:50:32.757+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:50:32.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:50:32.757+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:50:32.774+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2023-05-16T21:51:03.275+0000] {processor.py:156} INFO - Started process (PID=5055) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:51:03.275+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:51:03.276+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:51:03.276+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:51:03.277+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:51:03.277+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:51:03.278+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:51:03.301+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.028 seconds
[2023-05-16T21:51:33.698+0000] {processor.py:156} INFO - Started process (PID=5114) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:51:33.705+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:51:33.706+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:51:33.705+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:51:33.708+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:51:33.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:51:33.708+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:51:33.725+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.028 seconds
[2023-05-16T21:52:04.229+0000] {processor.py:156} INFO - Started process (PID=5173) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:52:04.236+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:52:04.237+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:52:04.237+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:52:04.241+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:52:04.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:52:04.242+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:52:04.259+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2023-05-16T21:52:34.707+0000] {processor.py:156} INFO - Started process (PID=5233) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:52:34.708+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:52:34.710+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:52:34.709+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:52:34.713+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:52:34.712+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:52:34.714+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:52:34.734+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2023-05-16T21:53:05.248+0000] {processor.py:156} INFO - Started process (PID=5292) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:53:05.255+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:53:05.256+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:53:05.255+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:53:05.257+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:53:05.257+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:53:05.258+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:53:05.275+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2023-05-16T21:53:35.755+0000] {processor.py:156} INFO - Started process (PID=5351) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:53:35.756+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:53:35.757+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:53:35.756+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:53:35.758+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:53:35.758+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:53:35.759+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:53:35.780+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.027 seconds
[2023-05-16T21:54:06.196+0000] {processor.py:156} INFO - Started process (PID=5410) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:54:06.197+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:54:06.197+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:54:06.197+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:54:06.199+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:54:06.199+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:54:06.199+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:54:06.217+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.023 seconds
[2023-05-16T21:54:36.767+0000] {processor.py:156} INFO - Started process (PID=5469) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:54:36.768+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:54:36.769+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:54:36.769+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:54:36.772+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:54:36.771+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:54:36.773+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:54:36.791+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2023-05-16T21:55:07.280+0000] {processor.py:156} INFO - Started process (PID=5528) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:55:07.281+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:55:07.282+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:55:07.282+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:55:07.285+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:55:07.285+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:55:07.286+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:55:07.304+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2023-05-16T21:55:37.877+0000] {processor.py:156} INFO - Started process (PID=5587) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:55:37.883+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:55:37.884+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:55:37.884+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:55:37.886+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:55:37.886+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:55:37.887+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:55:37.904+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2023-05-16T21:56:08.209+0000] {processor.py:156} INFO - Started process (PID=5646) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:56:08.210+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:56:08.210+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:56:08.210+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:56:08.212+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:56:08.211+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:56:08.212+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:56:08.229+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.022 seconds
[2023-05-16T21:56:38.515+0000] {processor.py:156} INFO - Started process (PID=5704) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:56:38.522+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:56:38.523+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:56:38.523+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:56:38.526+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:56:38.525+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:56:38.527+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:56:38.546+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2023-05-16T21:57:08.897+0000] {processor.py:156} INFO - Started process (PID=5763) to work on /opt/airflow/dags/first_dag.py
[2023-05-16T21:57:08.901+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2023-05-16T21:57:08.905+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:57:08.904+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2023-05-16T21:57:08.918+0000] {logging_mixin.py:149} INFO - [2023-05-16T21:57:08.913+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14
    description = "This is first airflow dag"
              ^
SyntaxError: invalid syntax
[2023-05-16T21:57:08.920+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2023-05-16T21:57:09.028+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/first_dag.py took 0.149 seconds
